### ISSUE TITLE
Cannot Start Charging session

### ISSUE THREAD

**Issue by MrRamsus** [bluecurrent/ha-bluecurrent#60]
## System Information

version | core-2024.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.0
Stage | running
Available Repositories | 1393
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 18.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | oracle
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.6.2), File editor (5.8.0), Terminal & SSH (9.14.0), MariaDB (2.7.1), Studio Code Server (5.15.0), Filebrowser (2.23.0_14), Cloudflared (5.1.19), Nginx Proxy Manager (1.0.1), Volvo2Mqtt (1.9.6), Mosquitto broker (6.4.1), Grafana (10.0.0), InfluxDB (5.0.0), InfluxDB v2 (v0.0.4), ZeroTier One (0.18.0), SQLite Web (4.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 5
views | 4
mode | storage

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bluecurrent/ha-bluecurrent/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When I press the. "Start Session" button to start my charging session, I'm not able to start the session. Probably because the default charging card is not set correctly (anymore).

### Reproduction steps

1. Plug my car into the charger
2. Go to my configured Integration "BlueCurrent"
3. Click on "Start session"
...
![image](https://github.com/user-attachments/assets/6d6f9838-0756-4e55-a6d3-4eaaf02b72e3)

### Debug logs

```text
2024-08-27 09:00:46.977 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall blue_current.start_session (c:01J69A65812MXXPZ2F6XXVG2GW): evse_id=BCU200529>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2783, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blue_current/__init__.py", line 90, in handle_start_session
    await client.start_session(evse_id, config_entry.data[CARD])
```

### Diagnostics dump

Not available

**Comment by HedzerHA** [comment]
Here the same.
When pressing the "start session" button, nothing happens.
I have selected a standard charge card, but the charge won't start.

Can you fix this so it can be just for automation in HA.

thank you.

**Comment by HedzerHA** [comment]
Got it working.
The problem is that there is no CARD number defined, So when you click te "start session" button it won't start.
I've coded my CARD number into `config_entry.data` and now it works.

But it would be eassier when you can put youre cardnumber into 'secrets.yaml' or someting like that.
